[package]
name = "eyefuck"
version = "0.1.0"
edition = "2024"

[dependencies]
brainfuck_compiler = { path = "crates/brainfuck_compiler" }
clap = { version = "4.5.51", features = ["derive"] }
colored = "3.0.0"
